### ISSUE TITLE
Podcasts: Ad Notification does not disappear

### ISSUE THREAD

**Issue by gahujipo** [aleab/toastify#21] opened 2017-11-15 07:09 UTC
Hi, I just installed your fork of toastify. I really like it. But when I play podcasts, Toastify shows a notification for ads and does not disappear. The same behaviuor I had on the original toastify. https://github.com/nachmore/toastify/issues/12#issuecomment-344504242

**Comment by aleab** [comment] 2017-11-15 07:52
Hi gahujipo, thanks for the issue report.
I'll look into this soon (tm).

**Comment by aleab** [comment] 2017-11-15 19:00
Unfortunately, I was not able to exactly reproduce your issue, although I know for sure podcasts are not currently supported by Spotify's public APIs. In particular, I couldn't reproduce the *"does not disappear"* part.
Are you using the latest version of Toastify? Are you sure the Settings window was not open?
Try to uninstall Toastify, delete the settings file located in *"%AppData%\Toastify\Toastify.xml"* and any residual file in the installation directory, and finally re-install the latest version.

Anyway, I've made some changes in the code in the latest commits that may partially deal with your issue. They will be implemented in the next release, surely not before next year.
If you have any experience with Visual Studio (2017, the Community Edition is free, or VS Code) you can try to build Toastify by your own and see if those few commits since v1.10.0 fixed the issue.

**Comment by gahujipo** [comment] 2017-11-17 11:14
Thank you for getting back to me so fast. I stopped Toastify, deleted the config file and reinstalled it. After that I've seen why you weren't able to reproduce the issue. It is because I have disabled the "only Show Toast when Hotkey is pressed"-option. This shows me a toast on every song change. I really like that. But when it comes to podcast the toast does not disapper (as it does for normal songs after 2-3 seconds) and shows "Spotify Ad - by". 

Could you maybe test the current master with the option mentioned above disabled, as i have no C# development environment at the moment? 
Thank you again!

**Comment by aleab** [comment] 2017-11-17 17:27
I just tested both the current version of master (68c9342) and the latest released version (v1.10.0) with both that option enabled and disabled, on both the desktop version of Spotify and the Windows Store one.
Here's the result. (OPT is the *"Only Show Toast when Hotkey is pressed"* option)

### Version 1.10.0
- If a regular song is playing and then you switch to a podcast, Toastify continues to show the song's information in the toast, no matter if OPT is enabled or not.
When the podcast reaches the end of the last episode or you use the *NextTrack* hotkey while listening to the last episode, then the toast displays the "Spotify Ad" thing; if the same podcast or another podcast is played, Toastify continues to show "Spotify Ad".
- If OPT is enabled and the *ShowToast* hotkey is pressed while playing a podcast, the toast appears and then disappears correctly.
- If OPT is disabled and the *NextTrack* hotkey is pressed (or the current track ends) while listening to a podcast, no toast is shown, unexpectedly; if the *ShowToast* hotkey is pressed, the toast appears and then disappears correctly.

### Current version of master
- If a regular song is playing and then you switch to a podcast, **the toast will now show "[Unknown Track Type]"** (currently, there's no way to get information on the podcast other than the track length and current time).
- If OPT is enabled and the *ShowToast* hotkey is pressed while playing a podcast, the toast appears and then disappears correctly.
- If OPT is disabled and the *NextTrack* hotkey is pressed (or the current track ends) while listening to a podcast, **the toast appears as expected** and then disappears correctly; if the *ShowToast* hotkey is pressed, the toast appears and then disappears correctly.

As you can see, I still couldn't reproduce the issue, as the toast always disappears correctly for me.
Were you listening to a particular podcast when you had this issue? Can I have a link to the podcast you tried?

**Comment by Vankog** [comment] 2017-11-18 18:11
I can't reproduce the sticking toast neither. They disappear as expected. :-/

Maybe it is a platform thing? On what system are you running?
(me: win 10 home x64)

**Comment by gahujipo** [comment] 2017-11-20 16:15
I retried it today, always with [this podcast](https://open.spotify.com/show/1OLcQdw2PFDPG1jo3s0wbp). The toast does not appear again. With normal songs the toast appears as expected. 
But when I pause the podcast, the toast appears and when I resume the toast reappears, but isn't sticky anymore. I don't know why the behaviuor has changed today. 

I am using Windows 10 Enterprise x64. What changed from last week to today is that Trendmicro OfficeScan got an update, but I don't think that this has an effect on it. 

The appearing toast looks like this: 
![grafik](https://user-images.githubusercontent.com/26710574/33028441-466adb14-ce16-11e7-8294-db8cd798afc7.png)

let me know if i can do further tests. 
![grafik](https://user-images.githubusercontent.com/26710574/33028512-720a8990-ce16-11e7-89b9-062191d9dec4.png)

**Comment by gahujipo** [comment] 2017-11-20 16:16
> What Spotify version? 
![grafik](https://user-images.githubusercontent.com/26710574/33028573-96023a78-ce16-11e7-9fce-eed8ec696a07.png)

**Comment by aleab** [comment] 2017-11-20 17:04
> I retried it today, always with [this podcast](https://open.spotify.com/show/1OLcQdw2PFDPG1jo3s0wbp). The toast does not appear again.

What do you mean? The toast doesn't appear at all when you press the *ShowToast* hotkey (Ctrl-Alt-Space by default)? If that's the case, then you probably had the desktop background *focused* and the *"Disable Toast With Fullscreen Videogames"* option enabled; there's a bug (fixed in cdbd79e) that prevents the toast to show up in that situation.

Everything else is expected behaviour. Unfortunately, there's currently no way to get the podcast's and episode's titles or anything else involving podcasts, since Spotify hasn't yet implemented proper APIs for them.

**Comment by gahujipo** [comment] 2017-11-21 08:42
Okay, i did some further research. 
1. The  ShowToast hotkey worked always in my tests.
2. I realized why yesterday the toast did not show up. The toast shows only when the podcast starts playing from the beginning. When an episode was started previously and resumes after (I think) 00:00:05 then the toast does not appear. I am not sure if this is expected behaviour. 

But somehow I wasn't able to reproduce again the case that the toast doesn't go away. So sorry for making confusion, I think this issue is not needed anymore. @aleab feel free to close it.

**Comment by aleab** [comment] 2017-11-21 10:25
> I am not sure if this is expected behaviour.

You mean with the *"Only Show Toast when Hotkey is pressed"* option enabled? The current version behaves quite inconsistently with podcasts; in particular, most of the times the toast doesn't show up automatically when the episode changes or any other hotkey other than the *ShowToast* one is pressed.

> So sorry for making confusion, I think this issue is not needed anymore.

No worries! It was definitely not a waste of time, since it made me aware of the inconsistencies in behaviour with podcasts.

**Closed** 2017-11-21 10:27 UTC
Labels: Type: Bug?

**Comment by Vankog** [comment] 2017-11-21 13:59
@gahujipo It sounds to me like everything is working now as expected. Some problems you described with the toast not coming up and so on should be fixed in the upcoming release if I understand @aleab's descriptions correctly. 

Your sticking toast issue could have easily just been a .NET glitch. Maybe windows ran an update and the platform was a bit inconsistent. Sometimes rebooting helps indeed. ^^

**Comment by gahujipo** [comment] 2017-11-21 15:17
> You mean with the "Only Show Toast when Hotkey is pressed" option enabled? 

No, i have this option always disabled to show a toast everytime the song changes. I like that very much! 

> The current version behaves quite inconsistently with podcasts

okay, so I will wait for the next release where your commits were applied. It doesn't make much sense now to discuss about a non-up-to-date version. I will retest that behaviuor with the next release and reopen this case i needed.

**Comment by aleab** [comment] 2017-11-21 15:50
>> You mean with the "Only Show Toast when Hotkey is pressed" option enabled?

I actually meant disabled. My bad. ^^
