### ISSUE TITLE
Toastify not doing popups (global shortcuts working)

### ISSUE THREAD

**Issue by wintermute000** [aleab/toastify#83] opened 2018-07-30 06:15 UTC
If this is a crash, bug or unexpected behaviour report, please use the following template.

## EXPECTED BEHAVIOUR
Popup shows when track changes in spotify

## ACTUAL BEHAVIOUR
Popups don't happen when tracks change in spotify, whether desktop or tablet mode
Global shortcuts DO work

## STEPS TO REPRODUCE THE BEHAVIOUR
Latest toastify 1.10.8
Spotify from windows store
Win10 Pro 1803
Surface Pro

## LOG FILE

[Toastify.log](https://github.com/aleab/toastify/files/2239867/Toastify.log)

**Comment by aleab** [comment] 2018-08-01 13:17
Duplicate of #82

**Closed by aleab** 2018-08-01 13:17 UTC
