### ISSUE TITLE
Cannot run latest version

### ISSUE THREAD

**Issue by faridv** [aleab/toastify#34] opened 2018-03-07 13:22 UTC
I installed latest release but when running it, following errors come up and program never starts.

![image](https://user-images.githubusercontent.com/854874/37094309-bed2bef4-2227-11e8-9c16-e08a3fa01c98.png)

![image](https://user-images.githubusercontent.com/854874/37094314-c564dd56-2227-11e8-9aa8-93e802d9bf13.png)

I'm using 64bit version of Windows 8.1 and Spotify version of **1.0.75.483.g7ff4a0dc**.

This is the Toastify.log content:

```
16:48:57,028+03:30 INFO  [Toastify.EntryPoint.RunApp, 0] (1) – Architecture: IntPtr = 64bit, Is64BitProcess = True, Is64BitOS = True
16:48:57,050+03:30 INFO  [Toastify.EntryPoint.RunApp, 0] (1) – Toastify version = 1.10.2.30649
16:48:57,146+03:30 ERROR [Toastify.App.Application_DispatcherUnhandledException, 0] (1) – Unhandled Dispatcher exception.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Toastify.Helpers.ColorHelper.HexToColor(String hexColor)
   at Toastify.View.ToastView.InitToast()
   at Toastify.View.ToastView.Init()
   at Toastify.View.ToastView.Window_Loaded(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
16:49:00,119+03:30 ERROR [Toastify.EntryPoint.Main, 0] (1) – Unhandled top-level exception.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Toastify.Helpers.ColorHelper.HexToColor(String hexColor)
   at Toastify.View.ToastView.InitToast()
   at Toastify.View.ToastView.Init()
   at Toastify.View.ToastView.Window_Loaded(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   at System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   at MS.Internal.LoadedOrUnloadedOperation.DoWork()
   at System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at Toastify.EntryPoint.RunApp()
   at Toastify.EntryPoint.Main(String[] args)
```

**Comment by aleab** [comment] 2018-03-07 14:03
Thanks for the issue report, @faridv.
I already know the latest version doesn't currently work and I have a fix ready to be release soon. I just need a bit more time to test it thoroughly.

I'll let you know when it's released.

**Comment by aleab** [comment] 2018-03-07 14:04
Closing as duplicate of #30.

**Closed by aleab** 2018-03-07 14:04 UTC
Labels: Type: Duplicate

**Comment by aleab** [comment] 2018-03-08 01:03
@faridv, The new version has been release ([here](https://github.com/aleab/toastify/releases/latest))!
