### ISSUE TITLE
performance-bug: high CPU utilization

### ISSUE THREAD

**Issue by Vankog** [aleab/toastify#22] opened 2017-11-21 14:39 UTC
I realized by chance that Toastify is constantly using quite a lot of CPU performance (around 15% for me):
![toastify cpu utilization](https://user-images.githubusercontent.com/3804909/33077934-706dfc50-ced1-11e7-8b0b-02d4ab6c451c.png)

It does not matter whether it is the parent of Spotify or not.
I could also not pin down any context variables or settings that might have an impact on this.

It is just constantly using a bit too much CPU for such a low profile tool. ;-)
Do you mine some currency at least? ^^

**Comment by aleab** [comment] 2017-11-21 17:45
I have a much lower CPU usage. Comparing it with Spotify's, when Spotify is minimized it uses around 0.9%, while Toastify uses around 1.20%.
It's indeed quite alarming, not as much as on you system, but still...

Taking a look at the Threads tab of Process Explorer, I found *a few* threads started from `clr.dll!GetMetaDataPublicInterfaceFromInternal`, which take most of the CPU time (the main thread only takes 0.03% for me). That system library is the Common Language Runtime, which handles the .NET managed environment.

I'll do some performance profiling and see where this high CPU usage is coming from.

> Do you mine some currency at least? ^^

🤣

**Comment by Vankog** [comment] 2017-11-21 19:41
Just a wild guess, but:
![toastify cpu utilization stack](https://user-images.githubusercontent.com/3804909/33093028-1e8aea76-cefc-11e7-8d52-600b17eca9d9.png)
All those threads have LogHelp in their stack. Might this have something to do with the new logging system?

**Comment by aleab** [comment] 2017-11-21 20:58
Nope, it was not present in version 1.10.0.

However, I just figured out (silly me!) that those methods in the stack are not involved at all; they are just the base address of the base+offset addressing used.
So, for example, the actual method in the stack for TID 144796 is located at an offset of +0x4310 from the start of the LogHelp_TerminateOnAssert method.

Figured out that most of those methods in the stack are related to the CLR Thread Pool and at least 10 (in my case) of the threads listed by Process Explorer are worker threads instantiated by the thread pool (available in case of need?).

I'll have a look at ThreadPool's options to see if I can tweak something.

**Comment by Vankog** [comment] 2017-11-22 13:34
I already had hunch that the stack does not show the real methods.
I tried to configure the debug symbols in process explorer by adding this path:
`SRV*c:\symbols*http://msdl.microsoft.com/download/symbols`
![symbols](https://user-images.githubusercontent.com/3804909/33129962-09155af0-cf92-11e7-835f-a871324dde17.png)
But it seems they are not downloaded currently. The URL resolves to exceptions as it seems.

**Comment by aleab** [comment] 2017-11-22 13:44
I had to change the *"Dbghelp.dll path"* to the *dbghelp.dll* that comes with the [Debugging Tools for Windows](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/): `%ProgramFiles(x86)%\Windows Kits\10\Debuggers\x64\dbghelp.dll`.
Apparently the default one can't resolve addresses to method names.

**Comment by Vankog** [comment] 2017-12-14 00:12
It is getting worse. Now it routinely runs at around 23%, tendency rising.
Even just now, after restarting it, this level rose just again to about 27%.

Also, memory allocation of about 25MB seems quite much as well.

Maybe there is something aggregating over time that increases the footprint? Some logs, analytics or something?

**Comment by aleab** [comment] 2017-12-14 15:49
I've done some CPU profiling and I think I've identified a couple of methods that might be causing this excessive CPU usage. I've already addressed one of them with a temporary fix (to properly address it, I might need to push some changes onto the SpotifyAPI-NET project); I still need to figure out how to change the other one(s).

Also, since this problem seems to be much worse and more noticeable on your PC than mine, I would like you (if you don't mind, obviously 😉) to give a try to [this](https://github.com/aleab/toastify/files/1559615/ToastifyInstaller.zip) build.
The CPU usage on my end decreased slightly from 1.4-1.7% to 0.6-0.8%; I expect yours to decrease by the same ratio.
<br/>

> Also, memory allocation of about 25MB seems quite much as well.

Unfortunately, the high memory usage is one of the major trade-offs when using C#.
I wouldn't really worry about that unless there are memory leaks and the memory footprint increases over time (and it doesn't, as far as I know).
Anyway, Ive also done some memory profiling and results are fine except for one method in the SpotifyAPI-NET that keeps allocating/deallocating memory periodically. I don't think that can be changes, though.
<br/>

> Btw: I think the log file should not be located in appdata\roaming (%appdata%), but in appdata\local (%localappdata%). It is nothing we need to sync. 😉

Good point!

**Comment by Vankog** [comment] 2017-12-14 20:42
Alright, the whole issue seems to be context sensitive as well.
Today Toastify (official build) only utilizes around 5%. All I did was installing the current Windows 10 update and a restart.
I closed both apps and restarted them.
This time Toastify used around 7%.
Yet another third and fourth round, this time at around 6%. 
I sort of was expecting to see it rise with every start, but that's not the case at it seems.

Your test build seems to hit the spot quite well so far - in parts at least.
Upon several runs, constantly this result: 
Around 2%(!). However, ONLY when playing. On pause the utilization goes up to around 6,5% again. 😨
On play it sinks again.   
But: Even Spotify suddenly only utilizes around 3,5%, which amounts to 1% less (context: minimized and playing, steered to a playlist to minimize the impact of the animated home page.)

**Comment by aleab** [comment] 2017-12-14 23:57
> On pause the utilization goes up to around 6,5% again. 😨

😱 I'll have a look at it tomorrow.
<br/>

> Spotify suddenly only utilizes around 3,5%, which amounts to 1% less

That is expected. The high CPU usage in Toastify was partially caused by periodic HTTP requests to the local server run by the Spotify client; because of these requests, Spotify itself was having a higher CPU usage as well. What changed is that I removed some of these requests and retrieved whatever I needed in some other way, without making requests to the local server.

**Comment by Vankog** [comment] 2017-12-15 04:15
I guess the progress bar is quite expensive, isn't it?

Alright, I'm excited about future developments. :-)

**Comment by aleab** [comment] 2017-12-15 12:50
It's not expensive at all, at least no more than calling a method, updating the value of a variable and refreshing the view.
Basically it works like this. There is a component in the SpotifyAPI-NET library that periodically (by default, every 100ms, I think) makes a request to the server to get the current status of the Spotify client; depending on how the status changed, it raises some of its events, including `OnTrackTimeChange`, that is the one I use to update the progress bar.
The problem is that sometimes, some of the events are not raised (for example when listening to podcasts), or I need more information than a particular event's args provide; so I needed to make the request myself to be able to get a status from Spotify.
What I did is remove these extra requests and get (through reflection, at the moment) the latest stored status from the component in the SpotifyAPI-NET library.

**Comment by Vankog** [comment] 2017-12-16 16:37
Another day another measure. (just because I was curious)
Today the Toastify test build uses around 9% on play and 18% on pause:
The spike in IO is when the plays/pause took place.
![toastify cpu utilization](https://user-images.githubusercontent.com/3804909/34072326-9945a732-e285-11e7-8372-dd72bcb021b8.png)

This time the memory pressure on my system in general is higher and the system is running for 2 1/2 days (counted with hibernation time included).

It is quite interesting to see these differences in CPU utilization with differences in uptime and probably global memory and CPU pressure. This hints at issues that are a bit deeper.

**Comment by aleab** [comment] 2017-12-16 18:43
It is interesting indeed!

That constant IO activity and those spikes are also quite interesting. I found out that the spikes are somehow caused by the logger; I raised the minimum log level for Release builds and they were gone. 😕
I don't know where that constant IO activity comes from, though. I bet it's something in the SpotifyAPI-NET library.

**Comment by Vankog** [comment] 2017-12-16 19:29
The I/O is Network I/O exclusively. So I thought it's the communication with the Spotify server and RPCs (not sure if those show up as network I/O, though). Was this a wrong assumption?

**Comment by aleab** [comment] 2017-12-16 19:56
Honestly, I'm not sure what Process Explorer is actually showing there; it's probably a combination of disk and network activity. That constant I/O is probably what you assumed. The spikes are definitely disk I/O.

**Comment by aleab** [comment] 2018-01-15 17:45
I'll close this issue for now. It's been addressed in the new version.

**Closed by aleab** 2018-01-15 17:45 UTC
Labels: Type: Maintenance
