### ISSUE TITLE
Open Spotify by Clicking Toast while Spotify is minimised to System Tray

### ISSUE THREAD

**Issue by mjordanBetBright** [aleab/toastify#56] opened 2018-03-20 14:36 UTC
## EXPECTED BEHAVIOUR
Clicking on the Toast Notification used to open Spotify when closed

## ACTUAL BEHAVIOUR
It only opens if Spotify has been minimised

## STEPS TO REPRODUCE THE BEHAVIOUR
Close Spotify (minimised to tray)
Open Toastify notification
Click on it
Spotify should open, but does not

If Spotify is minimised to the taskbar, clicking on the toast works. This is only when Spotify is minimised to the System Tray

## LOG FILE
[Toastify.log](https://github.com/aleab/toastify/files/1829731/Toastify.log)

**Comment by aleab** [comment] 2018-03-20 14:40
Duplicate of #48.
Unfortunately I can't fix it.

**Closed by aleab** 2018-03-20 14:40 UTC

**Comment by mjordanBetBright** [comment] 2018-03-20 14:43
I should've searched for that. Sorry for the duplicate. Thanks for the response and great work on the tool.
