### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by entozoon** [aleab/toastify#30] opened 2018-03-01 09:09 UTC
```---------------------------
Unhandled exception
---------------------------
Unhandled Dispatcher exception.
Object reference not set to an instance of an object.
---------------------------
OK   
---------------------------
```

Running latest release (v1.10.2) on Win 7,

**Comment by abelgomez** [comment] 2018-03-01 14:01
Same problem here, with Spotify version 483.g7ff4a0dc

**Comment by aleab** [comment] 2018-03-01 14:32
@entozoon, I may sound a bit arrogant here; I'm sorry.
I've created an issue template to avoid this kind of reports. An ASCII representation of a message box is not really helpful, don't you think?
Do you mind attaching your latest log file here? You can find it in `%LocalAppData%\Toastify` (for example, `C:\Users\Michael\AppData\Local\Toastify\Toastify.log`)

@abelgomez, thanks. :+1:  That log file is really helpful. I'll work on a fix in this weekend, probably.

**Comment by aleab** [comment] 2018-03-01 15:19
Quick, dirty fix. Do you mind checking if this test build works? @entozoon @abelgomez 

[ToastifyInstaller.zip](https://github.com/aleab/toastify/files/1771645/ToastifyInstaller.zip)

**Comment by abelgomez** [comment] 2018-03-01 15:21
Thank you very much for your quick response, but unfortuately, does not work for me :( Please find attached the new log.
[Toastify.log](https://github.com/aleab/toastify/files/1771671/Toastify.log)

**Comment by aleab** [comment] 2018-03-01 15:36
Thank you very much. I know what the root cause of the issue is now.
The ETA for the fix is by the end of this weekend, hopefully.

**Comment by ferkanzai** [comment] 2018-03-02 11:46
[Toastify.log](https://github.com/aleab/toastify/files/1774894/Toastify.log)
I assume that now you have the problem located, but just in case, here is my log file! This is with the fix from yesterday installed. 

Keep the good work! Thanks!!

**Comment by aleab** [comment] 2018-03-03 20:02
I should have fixed this issue in the latest commit, but I haven't tested it thoroughly yet.
Do you guys mind checking **[this](https://github.com/aleab/toastify/files/1777827/ToastifyInstaller.zip)** out and see if it works correctly? Some settings might reset, especially toast colors and font size.

I'll release the official build by tomorrow evening (CET).

**Comment by ferkanzai** [comment] 2018-03-03 20:32
Hi!! 

Now it installs correctly, but for me, doesn't work. The hotkeys don't do anything. Sharing my log again, just in case! 

Thanks!!
[Toastify.log](https://github.com/aleab/toastify/files/1777864/Toastify.log)

**Comment by aleab** [comment] 2018-03-03 20:50
Yeah, you are correct.
Are you using Spotify version 1.0.75.483.g7ff4a0dc? I just updated to it and hotkeys stopped working.
This might take a while longer to fix.

**Comment by aleab** [comment] 2018-03-03 21:24
Be sure to follow #31 to know when the new issue pointed out by @ferkanzai is resolved.

**Comment by ferkanzai** [comment] 2018-03-03 21:58
Yeah, that's the version I'm currently using! I'll try the #31 fix and tell you how it went! Thanks!!

**Comment by abelgomez** [comment] 2018-03-03 22:40
The version in https://github.com/aleab/toastify/files/1777827/ToastifyInstaller.zip and also works for me and does not throw the exception anymore.

Nevertheless, I also suffer from the problem in #31 😞 

Indeed, #31 was what made me to install the latest release, but I see that the issue has not been addressed yet :(

Thanks for your work 👍

**Comment by aleab** [comment] 2018-03-04 21:12
The fix that was expected to be released by this evening (CET) will unfortunately be delayed. I still don't have a definitive fix for the new issue (#31) and I'd like to bundle them together, since the app will still be broken for those who updated Spotify to v1.0.75.483.g7ff4a0dc.

I'm sorry for the delay. 😞

**Comment by abelgomez** [comment] 2018-03-04 21:23
Don't worry, thanks anyway.

For those who inadvertently updated Spotify: I was able to "downgrade" to version 1.0.74.380.g1fcff12a by installing Spotify frm the Windows Store.

**Comment by Blazeflack** [comment] 2018-03-05 01:09
I tested the version you posted last in this ticket @aleab and I noticed an issue that doesn't seem connected, but could be a side effect of recent changes.

When I opened the program for the first time it told me it couldn't find a cfg file, told me to find it and delete it, and told me it would load with default settings. Nothing too surprising there. I went through its settings and configured it to my liking.

After that I noticed some issues:
- When I wanted to change the volume step it threw an exception.
- Upon reopening the program the volume control had changed to Spotify instead of Mixer.
- Various other settings were now back to default values.
- Changing volume control to Mixer and then saving and reopening the program would result in still using Spotify.
- it would appear that the cfg file is only partially used, as a lot of settings would load with values that were not defined in the cfg file.

I imagine a lot of the issues above is a side effect of recent changes that haven't been completed, but I wanted to mention it just in case it has to be looked into further.

I didn't save the exception error, but I can get it if needed.

Thank you.

**Comment by aleab** [comment] 2018-03-05 01:23
@Blazeflack the majority of the strange behaviours you mentioned are indeed a side effect of unfinished/untested recent changes.

The issue related to the app not using setting values defined in the cfg file has been fixed in commit 28bcb18, pushed a couple of hours after I made available that test version.

**Comment by Blazeflack** [comment] 2018-03-05 01:32
Good to know, thank you :)

I will await the next release.

**Comment by henriklb** [comment] 2018-03-05 20:33
Thank you for your hard work. Looking forward to the next release!

**Comment by aleab** [comment] 2018-03-08 01:01
@xaarock, I loved that too; I've been using it since I added it, but unfortunately it just doesn't work anymore.

**Comment by Blazeflack** [comment] 2018-03-08 02:50
New release works correctly and I'm happy to be able to keybind without modifiers :).

Thanks.

**Comment by abelgomez** [comment] 2018-03-08 10:41
Works great @aleab , thank you for your quick fix.

**Comment by Kilay** [comment] 2018-03-08 12:27
The first time I launched Toastify after updated, I had this error :
![image](https://user-images.githubusercontent.com/314557/37151041-461ffc9e-22d4-11e8-831a-deea7e6f7367.png)

This is working well now, thanks.

**Comment by aleab** [comment] 2018-03-08 12:49
@Kilay, if you have that error message again, be sure to open a new issue report and include your log file.

**Comment by Kilay** [comment] 2018-03-08 13:42
Sure, but for now, I didn't had this message again. Even after restarting Toastify.

**Comment by andreasolsson80** [comment] 2018-03-09 05:35
Got the same problem with the latest version 1.10.3. Have attached the log file.

[Toastify.log](https://github.com/aleab/toastify/files/1795748/Toastify.log)

**Comment by aleab** [comment] 2018-03-09 06:23
@andreasolsson80, thanks for the report!
Your log file matches with the one posted in #37. Subscribe to that issue to get updates on its resolution.

**Closed** 2018-03-09 07:56 UTC
Labels: Type: Bug

**Comment by entozoon** [comment] 2018-03-09 16:07
Epic work @aleab; fix works great!
Apologies for the vague bug report but looks like the community rallied round and contributed :)
