### ISSUE TITLE
Toastify on startup

### ISSUE THREAD

**Issue by iChippy** [aleab/toastify#57] opened 2018-03-26 12:47 UTC
Not too sure if anyone else is getting the same issue that I am (hell maybe a fresh install will fix it I haven't tried yet) but when having toastify on startup it doesn't actually start, both toastify and Spotify will open but none of the toastify hotkeys work until I exit toastify and reopen it.

**Comment by aleab** [comment] 2018-03-26 19:10
Just tested with both the latest release and the current unreleased version of the master branch, and I couldn't reproduce your issue. Toastify and Spotify both start up and hotkeys work correctly.

**Comment by lazyb5** [comment] 2018-03-27 14:08
I can't get it to save the setting either. I just put a shortcut in the startup folder for now.

**Comment by aleab** [comment] 2018-03-27 14:25
@lazyb5 Yeah, that particular setting is currently bugged. Will be fixed in the next version, though.

**Comment by clarkycal** [comment] 2018-04-01 14:43
Going to bump this issue, as it still doesn't work for me even after the new release which fixed the saving bug. (Spotify doesn't start with windows)

**Comment by aleab** [comment] 2018-04-01 16:00
@clarkycal Yeah, I noticed it's still a bit glitchy, but the setting is saved correctly now. This time, the problem is that it resets to the default value only the first time you open the Settings window.
For now, the solution is to tick and untick the option a couple of times every time you open the Settings window.

I'll probably release an [other] hotfix soon™.

**Comment by aleab** [comment] 2018-04-02 02:15
Just released the hotfix. Sorry for the poor quality of the previous fix. 😓

**Comment by clarkycal** [comment] 2018-04-02 02:46
@aleab Cheers mate, I will report back if there are any issues! Thanks.

**Comment by clarkycal** [comment] 2018-04-02 14:51
I'm sorry, I'm not sure if I am doing something wrong. Just doesn't work, even after the hotfix.

**Comment by clarkycal** [comment] 2018-04-02 15:04
I have given you the new and old.
[Toastify.log](https://github.com/aleab/toastify/files/1868386/Toastify.log)
[Toastifyold.log](https://github.com/aleab/toastify/files/1868387/Toastifyold.log)

**Comment by aleab** [comment] 2018-04-02 15:31
There's nothing in there unfortunately.
Try following these steps:
1. Start Toastify, open the settings window and enable the *"Launch Toastify with Windows"* option (disable and re-enable it if it's already ticked)
2. Save but don't close the settings window
3. Press `Windows Key + R` on your keyboard and type `regedit`
    1. If you are on Windows 10, paste `Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run` in the text box right under the menu bar (the one under *"File"*, *"Edit"*, etc.) and hit Enter
    2. If you are not on Windows 10, I guess you have to navigate to that "folder" manually
4. In the right panel you should be able to see at least a couple of entries, *"(Default)"* and *"Toastify"*; if Toastify is not there, we have a problem we need to debug further.

**Comment by Vankog** [comment] 2018-04-02 15:38
Hm... might this be an issue with security/antivirus software?
Toastify has no certified signature, so maybe some security software blocks auto start.

Please check regedit `HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Run` for the Toastify entry.

**Comment by clarkycal** [comment] 2018-04-02 15:41
![untitled](https://user-images.githubusercontent.com/8182599/38202733-ac8a2da0-3694-11e8-9058-306491fb1bdc.png)
Toastify has access, so idk, i will check the reg key

**Comment by Vankog** [comment] 2018-04-02 15:50
If on Windows 10, also make sure that Toastify is activated in the Taskmanager -> Autostart tab.

**Comment by clarkycal** [comment] 2018-04-02 16:17
![untitled](https://user-images.githubusercontent.com/8182599/38204160-9f366e52-3699-11e8-9eec-629787826497.png)

![untitled2](https://user-images.githubusercontent.com/8182599/38204183-bf7c799a-3699-11e8-8962-86e9eda1646c.png)

**Comment by aleab** [comment] 2018-04-02 16:42
Let's try to debug this issue.
Follow these steps:
1. Re-open the Registry Editor and navigate to `Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run` as before.
2. Double click on *"Toastify"* and change `"C:\Program Files\Toastify\Toastify.exe"` to `"C:\Program Files\Toastify\Toastify.exe" --debug`.
3. Close the Registry Editor.
4. Go to `C:\Users\clark\AppData\Local\Toastify` and delete every log file.
5. Restart the computer.

**Comment by Vankog** [comment] 2018-04-02 16:42
Alright, everything seems in place.
The other entries do start, right? (steam, vibrance, dicord etc.)

**Comment by clarkycal** [comment] 2018-04-02 16:52
@Vankog Yep
@aleab  Alright done

**Comment by aleab** [comment] 2018-04-02 16:53
Oh, yeah, post the log file, please. Forgot to say that.

**Comment by clarkycal** [comment] 2018-04-02 16:55
eh, yeah, that's a problem, there isn't one since it didn't start. So you want me to manually start it?

**Comment by aleab** [comment] 2018-04-02 16:56
Nope, I just wanted to be sure it wasn't crashing at startup.

**Comment by clarkycal** [comment] 2018-04-02 16:56
it's like my windows won't even try to start it

**Comment by Vankog** [comment] 2018-04-02 17:05
Right. Let's do some basic checks, just to be sure:
Could you please make sure, that the path in the registry is actually correct? Maybe there is a bug and the path is a bit off or there is a faulty character in there.

1. Copy the path inside the registry key, hit windows-key (so the start menu opens) then ctrl+v then enter. Toastify should start. (with or without --debug, doesn't matter)

**Comment by Vankog** [comment] 2018-04-02 17:14
It seems you are not the only one with this issue:
https://stackoverflow.com/questions/45583405/why-does-my-c-sharp-application-not-start-automatically-on-logon
For whatever reason, the WOW6432Node\ node might actually work.

**Comment by clarkycal** [comment] 2018-04-02 17:23
I fixed it, For some reason, toastify and Spotify were set to run as admin, therefore this was stopping them from starting, removing that admin check allowed them to start.

**Comment by aleab** [comment] 2018-04-02 17:31
@clarkycal Awesome!

**Comment by aleab** [comment] 2018-04-02 17:43
> Wild guess: Is it possible the .NET runtime needs some startup time before an application can start?

I don't think so. As @clarkycal found out, the problem is that Toastify was set to run as admin, so the registry startup key wasn't working since I guess it required elevated priviledges.

I think this is a problem that needs to be addressed nonetheless for #49. Using a service might actually solve everything since we wouldn't need to use the registry *Run* key at all, but if I end up not using a service for that issue, we'll need to use the Tasks Scheduler maybe.

**Comment by aleab** [comment] 2018-04-11 13:58
@Tumpo that's strange. Do you mind trying out this version?
[ToastifyInstaller.zip](https://github.com/aleab/toastify/files/1899109/ToastifyInstaller.zip)

**Comment by Tumpo** [comment] 2018-04-12 08:35
@aleab I just noticed that last time I re-applied and did other stuffs (can't really recall what I did, I did many things) and now after several reboots keys have been working nicely without doing anything.

**Closed** 2018-04-12 18:01 UTC
Labels: Status: Feedback Needed, Type: Bug?
